global using DosPinos.HRMS.Entities.DTOs.Commons.Base;
global using DosPinos.HRMS.Entities.Interfaces.Commons.Base;
global using DosPinos.HRMS.Entities.Interfaces.Commons.Notification;
global using DosPinos.HRMS.Entities.Interfaces.Employees.Catalogs;
global using DosPinos.HRMS.Entities.Interfaces.Incapacities.Catalogs;
global using DosPinos.HRMS.Entities.Interfaces.Overtimes.Catalogs;
global using DosPinos.HRMS.Entities.Interfaces.Securities;
global using DosPinos.HRMS.Entities.Interfaces.Securities.Catalogs;
global using DosPinos.HRMS.Entities.Interfaces.WorkingDays.Catalogs;